---
- name: Erstellen von VMs auf einem ESXi-Host
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./serverlist.yml
    - ./accounts.yml

  tasks:
    - name: Sammle Informationen aller VMs
      community.vmware.vmware_guest_info:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        datacenter: "{{ item.datacenter_name }}"
        name: "{{ item.vm_name }}"
      delegate_to: localhost
      register: vm_infos
      loop: "{{ vm_configurations }}"

    - name: Initialisiere vm_lines
      set_fact:
        vm_lines: []

    - name: Sammle Hostnamen und MAC-Adressen fuer jede Netzwerkschnittstelle
      set_fact:
        vm_lines: "{{ vm_lines + [ guest_name + ';' + network['label'] + ';' + network['mac_address'] ] }}"
      loop: "{{ item.instance.network }}"
      loop_control:
        loop_var: network
      vars:
        guest_name: "{{ item.instance.guest_name }}"
      when: item.instance.network is defined
      with_items: "{{ vm_infos.results }}"
      loop_control:
        loop_var: item

    - name: Show VM lines
      debug:
        var: vm_lines

    - name: Speichere Hostnamen und MAC-Adressen in eine Datei
      copy:
        dest: "/tmp/vm_mac_list.csv"
        content: "{{ vm_lines | join('\n') }}"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: '0666'

    - name: Run Python for upload CSV to web
      ansible.builtin.command: python3 ./upload_mac_list.py